### ISSUE TITLE
Link webinar "How to Cut Corners and Stay Cool (webinar #15)" to blog articles

### ISSUE THREAD

**Issue by terales** [yegor256/blog#149]
[Webinar no. 15](https://www.youtube.com/watch?v=YBQoTZ-1X-o) is linked to these articles:
* http://www.yegor256.com/2015/01/15/how-to-cut-corners.html
* http://www.yegor256.com/2015/02/16/it-is-not-a-school.html

I'm going to create a PR for it with adding this video to `youtube` param.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue
