### ISSUE TITLE
Wrong image size in "Incremental Billing" post

### ISSUE THREAD

**Issue by Hohol** [yegor256/blog#154]
![screenshot](https://cloud.githubusercontent.com/assets/2988117/25266793/8860802c-2683-11e7-8469-792a80e01359.jpg)  
http://www.yegor256.com/2014/10/21/incremental-billing.html  
Other images in this page look fine. I use Chrome on Mac OS.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@Hohol what is your browser?

**Comment by Hohol** [comment]
@yegor256 I can't reproduce it anymore. Page looks fine today.
Browser is Google Chrome.

**Comment by yegor256** [comment]
@Hohol I believe the problem was fixed here: https://github.com/yegor256/jare/issues/31 Please, close the ticket

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/blog#154` was not in scope
