### ISSUE TITLE
Line number in code snippets

### ISSUE THREAD

**Issue by t-izbassar** [yegor256/blog#165]
Maybe you will consider adding line numbers in code snippets? I think it will encrease readability of your posts. Just a suggestion.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@t-izbassar I was doing that two years ago, but not anymore. In my opinion, they are not helping anyhow, but are making the code more difficult to copy-paste. Do you really need them?

**Comment by t-izbassar** [comment]
Well, not so much. I just was reading some of your posts and in that you was linking to line numbers from text. I guess that was an old one.
If code sample is really small and verbose there is no need in it. And I guess that you included line number in the code itself but it can be done through some css maybe so that it will not be the part of text code.
I just caught myself reading text with linking to line numbers and it was not great experience. Personally I don't want to pay attention and try to track count exact position and find out was what intention.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/blog#165` was not in scope
