### ISSUE TITLE
Copenhagen, Sweden?

### ISSUE THREAD

**Issue by filfreire** [yegor256/blog#200]
The blog post 

https://github.com/yegor256/blog/blob/033940f29bb56a81ee94fad7aa3f322d6ba01c29/_posts/2016/nov/2016-11-09-why-no-ebooks.md

the place is marked as Copenhagen, Sweden.

Copenhagen is in Denmark.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@filfreire thanks, my bad)

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/blog#200`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/blog#200` is not in scope.
