### ISSUE TITLE
Put link on agenda from main page

### ISSUE THREAD

**Issue by t-izbassar** [yegor256/blog#217]
I guess that it was like your personal plan on blog posts. Maybe add it as link on the main page?

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@t-izbassar it is linked from this page: http://www.yegor256.com/contents.html I don't want to link it from the home page, since it's very "drafty" and not accurate.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/blog#217` is not assigned, can't get start time

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/blog#217` was not in scope
