### ISSUE TITLE
add some more examples to Law of Demeter

### ISSUE THREAD

**Issue by ashtonhogan** [yegor256/blog#230]
This post isn't clear enough, what is the correct approach?
Some examples of the wrong approach?
This is a big factor in doing OOP correctly and I think this post could benefit from having a lot more information

blog/_posts/2016/jul/2016-07-18-law-of-demeter.md

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@ashtonhogan you can post these kind of comments/requests right in the blog, in the comments section. This issue tracker is for bugs, typos, technical problems, etc. Thanks.

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#230` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#230](https://github.com/yegor256/blog/issues/230) was not in scope
