### ISSUE TITLE
"Blame-Free Software Quality Control" article?

### ISSUE THREAD

**Issue by filfreire** [yegor256/blog#257]
@yegor256, in a recent commit, 

https://github.com/yegor256/blog/commit/778a3e818ccf57701d8326055a240d61e6d39826#diff-e31d69d96d4f33e66b0802adab28a13f , you deleted an article entitled "Blame-Free Software Quality Control".

I believe the article's content is of value and there would be benefit to the community in having a post or a page with this content. 

Was this in order to put it on an actual blog post?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RFVLU72) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@filfreire I will publish it in a magazine, that's the goal. Not on the blog.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
