### ISSUE TITLE
Wrong amazon link on "EO vol. 3"?

### ISSUE THREAD

**Issue by skapral** [yegor256/blog#261]
See http://www.yegor256.com/books.html.

There is an Amazon link on "Elegant Objects vol. 2" in the announced "Elegant Objects vol. 3 section. Was it done by mistake?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@skapral[/z](https://www.0crat.com/u/skapral) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RFVLU72) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@skapral fixed, thanks

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
