### ISSUE TITLE
Bold text doesn't seem to be rendering right on the blog.

### ISSUE THREAD

**Issue by nqafield** [yegor256/blog#262]
See this post:
http://www.yegor256.com/2018/04/24/right-way-to-report-bugs.html

The words "Victimize yourself" and "Push them" should be bold.

![image](https://user-images.githubusercontent.com/18754996/39205260-11de226a-47f2-11e8-930c-4031421f67de.png)

The raw md looks like this: `**Victimize yourself**` (**Victimize yourself**).

This bug appears on Windows 10 (Chrome, Brave) and Windows 7 (Chrome, IE).

@yegor256 say it works okay for him (presumably on Mac).

P.S. My entire world will collapse tomorrow if this isn't fixed... 😜

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@nqafield[/z](https://www.0crat.com/u/nqafield) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RFVLU72) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@nqafield fixed?

**Comment by yegor256** [comment]
@rultor deploy

**Comment by nqafield** [comment]
@yegor256 No, not fixed. Maybe not a big deal, but not fixed.
![image](https://user-images.githubusercontent.com/18754996/46575406-73d99f80-c9ac-11e8-8d90-63b73468827b.png)

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@nqafield how about now?

**Comment by nqafield** [comment]
@yegor256 Yep, working now.
