### ISSUE TITLE
editorial error

### ISSUE THREAD

**Issue by ashtonhogan** [yegor256/blog#263]
In [this](http://www.yegor256.com/2014/09/16/getters-and-setters-are-evil.html) article it says "There are a few arguments against "accessors" (another name for getters and setters)" but it should say "There are a few arguments against "accessors" (another name for getters ~~and setters~~)" because setters are called "mutators".

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@ashtonhogan[/z](https://www.0crat.com/u/ashtonhogan) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RFVLU72) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@ashtonhogan fixed in c463bcd6f1c thanks

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
