### ISSUE TITLE
Broken badge images

### ISSUE THREAD

**Issue by LenarBad** [yegor256/blog#277]
https://www.yegor256.com/pets.html

Images for Jare.io, S3Auth.com, Stateful.co, JCabi are not displayed

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@lenarbad[/z](https://www.0crat.com/u/lenarbad) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RFVLU72) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@LenarBad fixed, thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#277` is not assigned, can't get performer
