### ISSUE TITLE
"12 Best" page is broken

### ISSUE THREAD

**Issue by amihaiemil** [yegor256/blog#299]
Aparently the [12 Best](https://www.yegor256.com/best.html) page is broken, it displays all articles one under the other, as if they were loaded in iframes.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@amihaiemil[/z](https://www.0crat.com/u/amihaiemil) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RFVLU72) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@amihaiemil fixed, thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#299` is not assigned, can't get performer
