### ISSUE TITLE
The Contents page displays the content of the entire blog

### ISSUE THREAD

**Issue by NicharNET** [yegor256/blog#307]
The [Contents](https://www.yegor256.com/contents.html) webpage displays the content of the entire blog exposing Jekyll scripts, links, and all the images. The page takes too long to load because of its size. I guess there is some typo.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@nicharnet[/z](https://www.0crat.com/u/nicharnet) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RFVLU72) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@NicharNET fixed already, thanks!

**Comment by yegor256** [comment]
@rultor deploy

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#307` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
