### ISSUE TITLE
Post pages displays the page content twice

### ISSUE THREAD

**Issue by driver733** [yegor256/blog#308]
https://www.yegor256.com/2017/10/24/award-2018.html
https://www.yegor256.com/2018/09/18/fear-of-coupling.html
https://www.yegor256.com/2018/10/09/can-you-control-us.html
![screenshot 2018-10-10 at 13 42 33](https://user-images.githubusercontent.com/10466206/46731176-b3e1a080-cc92-11e8-818f-b7200a87a44b.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@driver733[/z](https://www.0crat.com/u/driver733) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RFVLU72) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@driver733 fixed, thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#308` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
