### ISSUE TITLE
_agile.md

### ISSUE THREAD

**Issue by yegor256** [yegor256/blog#359]
Let's review and publish.

**Comment by yegor256** [comment]
@nqafield please, review it and let's publish

**Comment by yegor256** [comment]
@0crat assign @nqafield

**Comment by 0crat** [comment]
> @0crat assign @nqafield  ([here](https://github.com/yegor256/blog/issues/359#issuecomment-496004936))

@yegor256 The job [#359](https://github.com/yegor256/blog/issues/359) assigned to @nqafield[/z](https://www.0crat.com/u/nqafield), here is [why](https://www.0crat.com/footprint/C3RFVLU72/b6790759-513d-44bc-a5cf-6e5becf67b6c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @nqafield[/z](https://www.0crat.com/u/nqafield) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by nqafield** [comment]
@yegor256 Could you assign it to @johndotpage please?

**Comment by yegor256** [comment]
@0crat assign @johndotpage

**Comment by 0crat** [comment]
> @0crat assign @johndotpage ([here](https://github.com/yegor256/blog/issues/359#issuecomment-496212808))

@yegor256 The job [#359](https://github.com/yegor256/blog/issues/359) assigned to @johndotpage[/z](https://www.0crat.com/u/johndotpage), here is [why](https://www.0crat.com/footprint/C3RFVLU72/821c1cfc-4cc5-428f-935b-e3243b603c70); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @johndotpage[/z](https://www.0crat.com/u/johndotpage) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@johndotpage done, thanks!

**Comment by 0crat** [comment]
Job [#359](https://github.com/yegor256/blog/issues/359) is not in the agenda of @johndotpage[/z](https://www.0crat.com/u/johndotpage), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 17 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#359](https://github.com/yegor256/blog/issues/359) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @johndotpage[/z](https://www.0crat.com/u/johndotpage)
