### ISSUE TITLE
_help

### ISSUE THREAD

**Issue by yegor256** [yegor256/blog#361]
Let's review and publish `_drafts/_help.md`

**Comment by yegor256** [comment]
@0crat assign @johndotpage

**Comment by 0crat** [comment]
> @0crat assign @johndotpage  ([here](https://github.com/yegor256/blog/issues/361#issuecomment-500361378))

@yegor256 The job [#361](https://github.com/yegor256/blog/issues/361) assigned to @johndotpage[/z](https://www.0crat.com/u/johndotpage), here is [why](https://www.0crat.com/footprint/C3RFVLU72/8d4586f6-ba36-44cf-a68a-07fa0a9f7257); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @johndotpage[/z](https://www.0crat.com/u/johndotpage) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@johndotpage are you on it?

**Comment by yegor256** [comment]
@rultor deploy

**Comment by 0crat** [comment]
Job was finished in 21 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#361](https://github.com/yegor256/blog/issues/361) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @johndotpage[/z](https://www.0crat.com/u/johndotpage)
