### ISSUE TITLE
Update copyright to 2019

### ISSUE THREAD

**Issue by aivinog1** [yegor256/blog#374]
For now, I see that at the bottom of the page: 
![изображение](https://user-images.githubusercontent.com/25925932/60876688-9748b800-a266-11e9-84bc-2b5052afeb0e.png) 
here: https://www.yegor256.com/2019/07/02/tdd-misbeliefs.html

I think that the last date should be in 2019.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@aivinog1[/z](https://www.0crat.com/u/aivinog1) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RFVLU72) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@aivinog1 you are right, thanks, fixed in fa2698eb7fa

**Comment by 0crat** [comment]
Job [#374](https://github.com/yegor256/blog/issues/374) is closed, can't start order

**Comment by 0crat** [comment]
Job [#374](https://github.com/yegor256/blog/issues/374) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#374](https://github.com/yegor256/blog/issues/374) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3RFVLU72/cee8dcf4-38f8-4485-8f08-21fbe052b754); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @aivinog1[/z](https://www.0crat.com/u/aivinog1)

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#374](https://github.com/yegor256/blog/issues/374) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
