### ISSUE TITLE
The link to the russian translate of the article How much do you cost is broken

### ISSUE THREAD

**Issue by aivinog1** [yegor256/blog#376]
In this article: https://www.yegor256.com/2014/10/29/how-much-do-you-cost.html the link to the translated article(http://karagodin.pro/how_much_do_you_cost/) is not working. See this: 
![Screenshot_2019-07-11-21-22-07-130_com android chrome](https://user-images.githubusercontent.com/25925932/61058733-fef73280-a421-11e9-9774-f6b8e5323ad1.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@aivinog1[/z](https://www.0crat.com/u/aivinog1) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RFVLU72) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@aivinog1 removed the link, thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#376` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
