### ISSUE TITLE
There are no numbers of visited cities and countries

### ISSUE THREAD

**Issue by nick318** [yegor256/blog#380]
There are no numbers of visited cities and countries on page - https://www.yegor256.com/talks.html
![image](https://user-images.githubusercontent.com/6926262/50422128-c1a1cd80-0860-11e9-8c29-851be51f7d31.png)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@nick318[/z](https://www.0crat.com/u/nick318) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RFVLU72) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#380` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
