### ISSUE TITLE
happiness

### ISSUE THREAD

**Issue by yegor256** [yegor256/blog#388]

**Comment by yegor256** [comment]
@0pdd assign @johndotpage

**Comment by yegor256** [comment]
@johndotpage can please check it? In the `_drafts` folder.

**Comment by johndotpage** [comment]
@yegor256 Sure. Btw, you assigned with @0pdd. Did you mean @0crat?

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/blog/issues/388#issuecomment-531556793); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by yegor256** [comment]
@johndotpage my bad

**Comment by yegor256** [comment]
@rultor deploy

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#388` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
