### ISSUE TITLE
evolutionary revolution

### ISSUE THREAD

**Issue by yegor256** [yegor256/blog#398]
Let's publish

**Comment by yegor256** [comment]
@0crat assign @johndotpage

**Comment by yegor256** [comment]
@johndotpage can you please review `_dratfs/_team.md` article?

**Comment by 0crat** [comment]
> @0crat assign @johndotpage  ([here](https://github.com/yegor256/blog/issues/398#issuecomment-546658319))

@yegor256 The job [#398](https://github.com/yegor256/blog/issues/398) assigned to @johndotpage[/z](https://www.0crat.com/u/johndotpage), here is [why](https://www.0crat.com/footprint/C3RFVLU72/034f7680-afbb-4eda-b3fa-b186cf1fc02a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @johndotpage[/z](https://www.0crat.com/u/johndotpage) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@johndotpage[/z](https://www.0crat.com/u/johndotpage) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor ping

**Comment by johndotpage** [comment]
Sorry @yegor256, I didn't mean to suggest it was ready to go yet. But I am on it right now.

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Comment by 0crat** [comment]
Job [#398](https://github.com/yegor256/blog/issues/398) is not in the agenda of @johndotpage[/z](https://www.0crat.com/u/johndotpage), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#398](https://github.com/yegor256/blog/issues/398) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @johndotpage[/z](https://www.0crat.com/u/johndotpage)
