### ISSUE TITLE
sql as a service

### ISSUE THREAD

**Issue by yegor256** [yegor256/blog#399]

**Comment by yegor256** [comment]
@0crat assign @johndotpage

**Comment by yegor256** [comment]
@johndotpage can you please review `_drafts/_sql.md` article?

**Comment by 0crat** [comment]
> @0crat assign @johndotpage  ([here](https://github.com/yegor256/blog/issues/399#issuecomment-546658353))

@yegor256 The job [#399](https://github.com/yegor256/blog/issues/399) assigned to @johndotpage[/z](https://www.0crat.com/u/johndotpage), here is [why](https://www.0crat.com/footprint/C3RFVLU72/c252be8e-f146-4288-8af3-57711c70bc40); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @johndotpage[/z](https://www.0crat.com/u/johndotpage) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@rultor deploy

**Comment by 0crat** [comment]
@johndotpage[/z](https://www.0crat.com/u/johndotpage) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@johndotpage[/z](https://www.0crat.com/u/johndotpage) resigned from [#399](https://github.com/yegor256/blog/issues/399), since the job is not in scope anymore

**Comment by 0crat** [comment]
The job [#399](https://github.com/yegor256/blog/issues/399) is now out of scope

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 12@b7e726625068, thread: PQ-C3RFVLU72
com.zerocracy.claims.ClaimIn[214] java.lang.IllegalArgumentException: Parameter "age" not found in "Order was canceled" among: [reason, priority, job, cause, _parent_sig, flow, voluntarily, login]
```

[0.50.34](https://github.com/zerocracy/farm): CID: [03687beb-7c21-4ef9-8def-19c830e0f1b5](https://www.0crat.com/footprint/C3RFVLU72/03687beb-7c21-4ef9-8def-19c830e0f1b5), Type: "Order was canceled"
