### ISSUE TITLE
suggestion to use different wording to improve clarity 

### ISSUE THREAD

**Issue by pluresideas** [yegor256/blog#407]
In your post here: _posts/2014/dec/2014-12-01-orm-offensive-anti-pattern.md

I would suggest replacing...

> Users of ORM **should** speak SQL (or its dialect, like HQL). 

with...

> Users of ORM **have to** speak SQL (or its dialect, like HQL). 

The users of ORM have no option they must/have to speak SQL in order to use it. That is your main point in the paragraph. I think this change would make the paragraph easier to understand.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@pluresideas[/z](https://www.0crat.com/u/pluresideas) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RFVLU72) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by pluresideas** [comment]
I was going to create a branch for this suggestion but it failed with 403:

> git push --set-upstream origin wording_change_suggestion
remote: Permission to yegor256/blog.git denied to pluresideas.
fatal: unable to access 'https://github.com/yegor256/blog.git/': The requested URL returned error: 403

**Comment by johndotpage** [comment]
@pluresideas Did you fork the repo?

**Comment by pluresideas** [comment]
@johndotpage I tried but it failed. The machine I am on is not setup correctly. I will try from a different machine later today and report back. Thanks!

**Comment by johndotpage** [comment]
@pluresideas I mean just fork it on github. That has nothing to do with your machine. Changes to these docs can be done entirely on this website. Fork the repo, edit the file, and then do a PR.

**Comment by pluresideas** [comment]
@johndotpage done: https://github.com/yegor256/blog/pull/408

Thanks for your help!

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#407` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
