### ISSUE TITLE
open source arm race

### ISSUE THREAD

**Issue by yegor256** [yegor256/blog#428]

**Comment by yegor256** [comment]
@0crat assign @johndotpage

**Comment by yegor256** [comment]
@johndotpage can you please help with `_drafts/os.md` article?

**Comment by 0crat** [comment]
> @0crat assign @johndotpage  ([here](https://github.com/yegor256/blog/issues/428#issuecomment-622025964))

@yegor256 The job [#428](https://github.com/yegor256/blog/issues/428) assigned to @johndotpage[/z](https://www.0crat.com/u/johndotpage), here is [why](https://www.0crat.com/footprint/C3RFVLU72/5da4eb8c-2703-45ce-aaab-0bf5330f00e4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @johndotpage[/z](https://www.0crat.com/u/johndotpage) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Comment by 0crat** [comment]
Job [#428](https://github.com/yegor256/blog/issues/428) is not in the agenda of @johndotpage[/z](https://www.0crat.com/u/johndotpage), can't set title
