### ISSUE TITLE
career killer

### ISSUE THREAD

**Issue by yegor256** [yegor256/blog#430]

**Comment by yegor256** [comment]
@0crat assign @johndotpage

**Comment by yegor256** [comment]
@johndotpage can you please help with `_drafts/_future.md`

**Comment by 0crat** [comment]
> @0crat assign @johndotpage  ([here](https://github.com/yegor256/blog/issues/430#issuecomment-626609287))

@yegor256 The job [#430](https://github.com/yegor256/blog/issues/430) assigned to @johndotpage[/z](https://www.0crat.com/u/johndotpage), here is [why](https://www.0crat.com/footprint/C3RFVLU72/e9282f65-099d-4df2-a3b0-175e0d328bf9); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @johndotpage[/z](https://www.0crat.com/u/johndotpage) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by johndotpage** [comment]
Sorry @yegor256! I've only just seen this (I'd got out of the habit of checking regularly - but back to it now). :)

I'll get on it this evening.

**Comment by yegor256** [comment]
@rultor deploy

**Comment by 0crat** [comment]
Job [#430](https://github.com/yegor256/blog/issues/430) is not in the agenda of @johndotpage[/z](https://www.0crat.com/u/johndotpage), can't set title
