### ISSUE TITLE
metrics

### ISSUE THREAD

**Issue by yegor256** [yegor256/blog#435]

**Comment by yegor256** [comment]
@0crat assign @johndotpage

**Comment by yegor256** [comment]
@johndotpage please, check `_drafts/metrics.md`

**Comment by 0crat** [comment]
> @0crat assign @johndotpage  ([here](https://github.com/yegor256/blog/issues/435#issuecomment-647171129))

@yegor256 The job [#435](https://github.com/yegor256/blog/issues/435) assigned to @johndotpage[/z](https://www.0crat.com/u/johndotpage), here is [why](https://www.0crat.com/footprint/C3RFVLU72/6740ce8b-d1dc-422d-b471-03ec52babaf4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @johndotpage[/z](https://www.0crat.com/u/johndotpage) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Comment by 0crat** [comment]
Job [#435](https://github.com/yegor256/blog/issues/435) is not in the agenda of @johndotpage[/z](https://www.0crat.com/u/johndotpage), can't set title

**Comment by 0crat** [comment]
Job was finished in 33 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
