### ISSUE TITLE
texsc article

### ISSUE THREAD

**Issue by yegor256** [yegor256/blog#450]

**Comment by yegor256** [comment]
@johndotpage can you please review `_drafts/texsc.md`

**Comment by yegor256** [comment]
@0crat assign @johndotpage

**Comment by 0crat** [comment]
> @0crat assign @johndotpage  ([here](https://github.com/yegor256/blog/issues/450#issuecomment-703302179))

@yegor256 The job [#450](https://github.com/yegor256/blog/issues/450) assigned to @johndotpage[/z](https://www.0crat.com/u/johndotpage), here is [why](https://www.0crat.com/footprint/C3RFVLU72/c083de0f-f5ed-4cec-ab0f-08da615e27d3); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @johndotpage[/z](https://www.0crat.com/u/johndotpage) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by yegor256** [comment]
@rultor deploy

**Comment by 0crat** [comment]
Job was finished in 34 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
