### ISSUE TITLE
blog post about problems

### ISSUE THREAD

**Issue by yegor256** [yegor256/blog#452]

**Comment by yegor256** [comment]
@0crat assign @johndotpage

**Comment by yegor256** [comment]
@johndotpage can you please review the blog post at `_drafts/problem.md`? thanks

**Comment by 0crat** [comment]
> @0crat assign @johndotpage  ([here](https://github.com/yegor256/blog/issues/452#issuecomment-706690085))

@yegor256 The job [#452](https://github.com/yegor256/blog/issues/452) assigned to @johndotpage[/z](https://www.0crat.com/u/johndotpage), here is [why](https://www.0crat.com/footprint/C3RFVLU72/76aaf3c5-e1fa-42d5-b8ed-a37e8f8e9e60); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @johndotpage[/z](https://www.0crat.com/u/johndotpage) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by yegor256** [comment]
@rultor deploy
