### ISSUE TITLE
encapsulation and coupling density

### ISSUE THREAD

**Issue by yegor256** [yegor256/blog#456]
Let's try to suggest a new metric: "density of coupling"

**Comment by yegor256** [comment]
@johndotpage can you please proof read this one: `_drafts/encapsulation.md`

**Comment by yegor256** [comment]
@0crat assign @johndotpage

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Comment by 0crat** [comment]
@johndotpage[/z](https://www.0crat.com/u/johndotpage) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@rultor deploy
