### ISSUE TITLE
article about planning

### ISSUE THREAD

**Issue by yegor256** [yegor256/blog#479]

**Comment by yegor256** [comment]
@johndotpage can you please help, it's in `drafts/plan.md`

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Comment by 0crat** [comment]
Job `gh:yegor256/blog#479` is not assigned, can't get performer
