### ISSUE TITLE
EO the Career Killer links to blogs are dead

### ISSUE THREAD

**Issue by Nikolas-Charalambidis** [yegor256/blog#590]
In the article https://www.yegor256.com/2020/05/13/career-killer.html there are two links to other blogs:

> Write a blog about OOP, like [@skapral](https://www.pragmaticobjects.com/) and [@g4s8](https://blog.g4s8.wtf/) are doing;

Both links are dead. Either they moved to a new domain or are no longer active.

**Comment by yegor256** [comment]
@Nikolas-Charalambidis I fixed them both, thanks!

**Comment by yegor256** [comment]
@rultor deploy
