### ISSUE TITLE
Broken links in "An Open Code Base Is Not Yet an Open Source Project"

### ISSUE THREAD

**Issue by nlif-m** [yegor256/blog#682]
Hello @yegor256,

There are broken links at https://www.yegor256.com/2018/05/08/open-source-attributes.html#contribution-guidelines

These links:
- https://github.com/yegor256/takes/blob/master/.github/ISSUE_TEMPLATE.md
- https://github.com/yegor256/takes/blob/master/.github/PULL_REQUEST_TEMPLATE.md

Accessing this links I expect to see some example of how to write my own GitHub issue and PR templates but get 404 error.

For some reason they were removed at https://github.com/yegor256/takes/commit/e6d034cf1f34a08e4d9913f129389c2b0d22c37f commit.

Thank you for the blog article.

**Comment by yegor256** [comment]
@nlif-m I fixed the links in dfb77a04c64, many thanks for noticing!
