### ISSUE TITLE
No 'Access-Control-Allow-Origin' header

### ISSUE THREAD

**Issue by kkamkou** [yegor256/blog#80]
![2015-07-25-6146d02](https://cloud.githubusercontent.com/assets/305739/8890019/56228160-32f0-11e5-98e3-01a853b6430f.png)

*chrome

**Comment by yegor256** [comment]
@kkamkou hm... something is wrong on your side, I suspect. The header is present there, see:

<img width="940" alt="screen shot 2015-07-26 at 9 51 38 am" src="https://cloud.githubusercontent.com/assets/526301/8892992/ff3bbbaa-337b-11e5-8404-39a1caac1ffb.png">

**Comment by kkamkou** [comment]
The font itself is okay, I can't see icons.
![2015-07-26-78cebf0](https://cloud.githubusercontent.com/assets/305739/8893080/ba1dc55e-3380-11e5-838b-b981cf1d2ba8.png)

**Comment by yegor256** [comment]
@kkamkou according to your screenshot, you don't see the font (Cambria) and icons. The font rendered on your screenshot is Georgia. Can you refresh again and send a new screenshot please?

**Comment by kkamkou** [comment]
![2015-07-26-531f9c3](https://cloud.githubusercontent.com/assets/305739/8893112/c727a9a2-3382-11e5-806c-37e0195fc02f.png)

**Comment by yegor256** [comment]
@kkamkou what is left, what is right? )

**Comment by kkamkou** [comment]
Cambria left, Georgia right

**Comment by yegor256** [comment]
@kkamkou yeah, I got that, but how can I reproduce the left and how the right one?

**Comment by kkamkou** [comment]
Well, I'm not sure that we're trying to fix the icons problem ). Let me post a new screen from a windows machine.
<img width="515" alt="untitled picture" src="https://cloud.githubusercontent.com/assets/305739/8893944/a600d006-33a4-11e5-829c-c81577ffcfbe.png">

Also, could u check this [comment](https://github.com/yegor256/blog/issues/80#issuecomment-124957552)

**Comment by yegor256** [comment]
@kkamkou yes, you're right, this header is not present for the icon font... thanks for reporting, let me investigate and fix
